function V = volume(nodes, tetrahedra, ind_m)
% TILAVUUS - Calculates a volume V from a given set of finite element nodes,
% the corresponding tetrahedra and suitable index matrix ind_m.
%
% TODO: Explain the structure of the nodes and tetrahedra.

    % A helper matrix to make the calculation more readable
    %
    % TODO: What does indexing into the nodes with the tetrahedra represent,
    % exactly? I guess the nodes which comprise the tetrahedra are selected?

    aux_mat = [
            nodes(tetrahedra(:,1),:)';
            nodes(tetrahedra(:,2),:)';
            nodes(tetrahedra(:,3),:)'
        ] - repmat(nodes(tetrahedra(:,4),:)',3,1);

    % The volume itself

    V = 1 / 6 * abs(               ...
            aux_mat(ind_m(1,1),:)  ...
            .*                     ...
            (aux_mat(ind_m(2,2),:) ...
            .*                     ...
            aux_mat(ind_m(3,3),:)  ...
        -                          ...
            aux_mat(ind_m(2,3),:)  ...
            .*                     ...
            aux_mat(ind_m(3,2),:)) ...
        -                          ...
            aux_mat(ind_m(1,2),:)  ...
            .*                     ...
            (aux_mat(ind_m(2,1),:) ...
            .*                     ...
            aux_mat(ind_m(3,3),:)  ...
        -                          ...
            aux_mat(ind_m(2,3),:)  ...
            .*                     ...
            aux_mat(ind_m(3,1),:)) ...
        +                          ...
            aux_mat(ind_m(1,3),:)  ...
            .*                     ...
            (aux_mat(ind_m(2,1),:) ...
            .*                     ...
            aux_mat(ind_m(3,2),:)  ...
        -                          ...
            aux_mat(ind_m(2,2),:)  ...
            .*                     ...
            aux_mat(ind_m(3,1),:)) ...
    );

    return V
end
