function s_points = zef_cem_electrode(zef,s_points)

if isempty(s_points)
    s_points = [];
else
    current_sensors = eval('zef.current_sensors');
    s_points = [ ...
        s_points(:,1:3), ...
        eval(['zef.' current_sensors '_electrode_outer_radius(:)']), ...
        eval(['zef.' current_sensors '_electrode_inner_radius(:)']), ...
        eval(['zef.' current_sensors '_electrode_impedance(:)']) ...
        ];
end
end
