%Copyright © 2018, Sampsa Pursiainen
zef.inv_synth_source = str2num(get(zef.h_inv_synth_source_1 ,'string')); 
zef.inv_synth_source = zef.inv_synth_source(:);
zef.inv_synth_source = [ zef.inv_synth_source ...
reshape(str2num(get(zef.h_inv_synth_source_2 ,'string')),size(zef.inv_synth_source,1),size(zef.inv_synth_source,2)) ...
reshape(str2num(get(zef.h_inv_synth_source_3 ,'string')),size(zef.inv_synth_source,1),size(zef.inv_synth_source,2)) ...
reshape(str2num(get(zef.h_inv_synth_source_4 ,'string')),size(zef.inv_synth_source,1),size(zef.inv_synth_source,2)) ...
reshape(str2num(get(zef.h_inv_synth_source_5 ,'string')),size(zef.inv_synth_source,1),size(zef.inv_synth_source,2)) ...
reshape(str2num(get(zef.h_inv_synth_source_6 ,'string')),size(zef.inv_synth_source,1),size(zef.inv_synth_source,2)) ...
reshape(str2num(get(zef.h_inv_synth_source_7 ,'string')),size(zef.inv_synth_source,1),size(zef.inv_synth_source,2)) ...
repmat(str2num(get(zef.h_inv_synth_source_8 ,'string')),size(zef.inv_synth_source,1),1) ...
repmat(str2num(get(zef.h_inv_synth_source_9 ,'string')),size(zef.inv_synth_source,1),1) ...
repmat(get(zef.h_inv_synth_source_10 ,'value'),size(zef.inv_synth_source,1),1) ...
];
zef.inv_synth_source(:,4:6) = zef.inv_synth_source(:,4:6)./repmat(sqrt(sum(zef.inv_synth_source(:,4:6).^2,2)),1,3);

