function [G, dipole_locations] =  zef_lead_field_interpolation( ...
    p_nodes, ...
    p_tetrahedra, ...
    p_brain_inds, ...
    p_source_model, ...
    p_intended_source_inds, ...
    p_regparam ...
)

    % Chooses the interpolation method based on given source_model and
    % constructs the interpolation matrix G and interpolation (dipole)
    % positions. Errors in case of unknown source model.
    %
    % Input (must be given even if not used, 'cause nobody wants to spend time
    % parsing the varargin tuple):
    %
    % - p_nodes (common)
    % - p_tetrahedra (common)
    % - p_brain_inds (common)
    % - p_source_model (common).
    % - p_intended_source_inds (Whitney and Hdiv)
    % - p_regparam (St Venant)
    %
    % Output:
    %
    % - Interpolation matrix G
    % - source_positions

    arguments
        p_nodes (:,3) double {mustBeNonNan}
        p_tetrahedra (:,4) double {mustBeInteger, mustBeNonnegative}
        p_brain_inds (:,1) double {mustBeInteger, mustBeNonnegative}
        p_source_model
        p_intended_source_inds (:,1) double {mustBeInteger, mustBeNonnegative}
        p_regparam (1,1) double
    end

    switch ZefSourceModel.from(p_source_model)

        case ZefSourceModel.Whitney

            [G, dipole_locations] = zef_whitney_interpolation( ...
                p_nodes, ...
                p_tetrahedra, ...
                p_brain_inds, ...
                p_intended_source_inds ...
            );

        case ZefSourceModel.Hdiv

            [G, dipole_locations] = zef_hdiv_interpolation( ...
                p_nodes, ...
                p_tetrahedra, ...
                p_brain_inds, ...
                p_intended_source_inds ...
            );

        case ZefSourceModel.StVenant

            [G, dipole_locations] = zef_st_venant_interpolation( ...
                p_nodes, ...
                p_tetrahedra, ...
                p_brain_inds, ...
                p_intended_source_inds, ...
                p_regparam ...
            );

        otherwise
            error("Unknown source model.");
    end

end
