function V = zef_tetra_volume(nodes, tetrahedra, take_absolute_value)
% VOLUME - Calculates a volume V from a given set of finite element nodes, the
% corresponding tetrahedra and suitable index matrix.

    % A helper matrix to make the calculation more readable
    %
    % TODO: What does indexing into the nodes with the tetrahedra represent,
    % exactly? I guess the nodes which comprise the tetrahedra are selected?

    aux_mat = [
            nodes(tetrahedra(:,1),:)';
            nodes(tetrahedra(:,2),:)';
            nodes(tetrahedra(:,3),:)'
        ] - repmat(nodes(tetrahedra(:,4),:)',3,1);

    % Index matrix used in the determinant calculation.

    ind_m = [1 4 7; 2 5 8 ; 3 6 9];

    % The volume itself as a determinant

    V = 1 / 6 * (                       ...
            aux_mat(ind_m(1,1),:)       ...
            .*                          ...
            (                           ...
                aux_mat(ind_m(2,2),:)   ...
                .*                      ...
                aux_mat(ind_m(3,3),:)   ...
                -                       ...
                aux_mat(ind_m(2,3),:)   ...
                .*                      ...
                aux_mat(ind_m(3,2),:)   ...
            )                           ...
        -                               ...
            aux_mat(ind_m(1,2),:)       ...
            .*                          ...
            (                           ...
                aux_mat(ind_m(2,1),:)   ...
                .*                      ...
                aux_mat(ind_m(3,3),:)   ...
                -                       ...
                aux_mat(ind_m(2,3),:)   ...
                .*                      ...
                aux_mat(ind_m(3,1),:)   ...
            )                           ...
        +                               ...
            aux_mat(ind_m(1,3),:)       ...
            .*                          ...
            (                           ...
                aux_mat(ind_m(2,1),:)   ...
                .*                      ...
                aux_mat(ind_m(3,2),:)   ...
                -                       ...
                aux_mat(ind_m(2,2),:)   ...
                .*                      ...
                aux_mat(ind_m(3,1),:)   ...
            )                           ...
    );

    if take_absolute_value
        V = abs(V);
    end
end
