function barycentra = zef_tetra_barycentra(nodes, tetrahedra)

    % Calculates the barycenters of the given tetrahedra (4-tuples of node
    % indices).

    arguments
        nodes (:,3) double {mustBeNonNan}
        tetrahedra (:,4) double {mustBeInteger, mustBePositive}
    end

    barycentra = 1 / 4 * ( ...
        nodes(tetrahedra(:,1),:) ...
        + ...
        nodes(tetrahedra(:,2),:) ...
        + ...
        nodes(tetrahedra(:,3),:) ...
        + ...
        nodes(tetrahedra(:,4),:) ...
    );
end
