open('zeffiro_interface_mesh_tool.fig');
zef.aux_handle_vec = [zef.h_pushbutton31;
zef.h_pushbutton20;
zef.h_pushbutton22; 
zef.h_checkbox14;
zef.h_checkbox15;
zef.h_checkbox_cp_on;
zef.h_edit_cp_a;
zef.h_edit_cp_b;
zef.h_edit_cp_c;
zef.h_edit_cp_d;
zef.h_edit80;
zef.h_edit81;
zef.h_edit82;
zef.h_visualization_type;
zef.h_pushbutton23;
zef.h_pushbutton21;
zef.h_pushbutton34;
zef.h_checkbox_mesh_smoothing_on;
zef.h_refinement_on;
zef.h_edit65;
zef.h_edit_meshing_accuracy; 
zef.h_edit75;
zef.h_smoothing_strength;
zef.h_pushbutton14;
zef.h_source_interpolation_on;
zef.h_popupmenu1;
zef.h_popupmenu6;
zef.h_popupmenu2;
zef.h_edit76];
uistack(flipud(zef.aux_handle_vec),'bottom');
rmfield(zef,'aux_handle_vec');
set(zef.h_pushbutton21,'callback','[zef.sensors,zef.reuna_p,zef.reuna_t] = process_meshes([]); [zef.nodes,zef.nodes_b,zef.tetra,zef.sigma_ind,zef.surface_triangles]=fem_mesh([]);zef.tetra_aux = zef.tetra; [zef.sigma,zef.brain_ind,zef.non_source_ind,zef.nodes,zef.tetra,zef.sigma_prisms,zef.prisms]=zef_sigma([]); zef.n_sources_mod = 1; zef.source_ind = []; set(zef.h_text_elements,''string'',num2str(size(zef.tetra,1)+size(zef.prisms,1))); set(zef.h_text_nodes,''string'',num2str(size(zef.nodes,1)));');
set(zef.h_pushbutton34,'callback','[zef.sigma,zef.brain_ind,zef.non_source_ind,zef.nodes,zef.tetra,zef.sigma_prisms,zef.prisms]=zef_sigma([]);set(zef.h_text_elements,''string'',num2str(size(zef.tetra,1)+size(zef.prisms,1))); set(zef.h_text_nodes,''string'',num2str(size(zef.nodes,1)));');
set(zef.h_popupmenu2,'string',{'Cartesian','Normal','Basis'});
set(zef.h_visualization_type,'string',{'Sigma','Recon. (volume)','Recon. (surface)'});
set(zef.h_pushbutton31,'string','Visualize volume');
zef_init_mesh_tool;