zef_data = zeffiro_interface_additional_options_app;

zef.h_additional_options = zef_data.h_additional_options;
zef.h_as_opt_2 = zef_data.h_as_opt_2;
zef.h_as_opt_1 = zef_data.h_as_opt_1;
zef.h_as_opt_3 = zef_data.h_as_opt_3;
zef.h_as_opt_4 = zef_data.h_as_opt_4;
zef.h_meshing_threshold = zef_data.h_meshing_threshold;
zef.h_as_opt_5 = zef_data.h_as_opt_5;
zef.h_as_opt_6 = zef_data.h_as_opt_6;
zef.h_cp2_on = zef_data.h_cp2_on;
zef.h_cp2_a = zef_data.h_cp2_a;
zef.h_cp3_on = zef_data.h_cp3_on;
zef.h_use_depth_electrodes = zef_data.h_use_depth_electrodes;
zef.h_source_model =  zef_data.h_source_model;
zef.h_colortune_param = zef_data.h_colortune_param;
zef.h_inv_hyperprior_weight = zef_data.h_inv_hyperprior_weight;
zef.h_cp_mode =  zef_data.h_cp_mode;
zef.h_brain_transparency = zef_data.h_brain_transparency;
zef.h_layer_transparency = zef_data.h_layer_transparency;
zef.h_inv_dynamic_range = zef_data.h_inv_dynamic_range;
zef.h_inv_scale = zef_data.h_inv_scale;
zef.h_inv_colormap = zef_data.h_inv_colormap;
zef.h_frame_start = zef_data.h_frame_start;
zef.h_frame_stop = zef_data.h_frame_stop;
zef.h_frame_step = zef_data.h_frame_step;
zef.h_orbit_1 = zef_data.h_orbit_1;
zef.h_orbit_2 = zef_data.h_orbit_2;
zef.h_reconstruction_type = zef_data.h_reconstruction_type;
zef.h_use_gpu = zef_data.h_use_gpu;
zef.h_parcellation_type = zef_data.h_parcellation_type;
zef.h_gpu_num = zef_data.h_gpu_num;
zef.h_parcellation_quantile = zef_data.h_parcellation_quantile;
zef.h_submesh_num = zef_data.h_submesh_num;
zef.h_inv_hyperprior = zef_data.h_inv_hyperprior;
zef.h_inv_hyperprior_tail_length_db = zef_data.h_inv_hyperprior_tail_length_db;
zef.h_cp2_b = zef_data.h_cp2_b;
zef.h_cp2_c = zef_data.h_cp2_c;
zef.h_cp2_d = zef_data.h_cp2_d;
zef.h_cp3_a = zef_data.h_cp3_a;
zef.h_cp3_b = zef_data.h_cp3_b;
zef.h_cp3_c = zef_data.h_cp3_c;
zef.h_cp3_d = zef_data.h_cp3_d;

zef.h_additional_options = zef_data.h_additional_options;
zef.h_as_opt_2.ValueChangedFcn = 'zef_update_options;';
zef.h_as_opt_1.ValueChangedFcn = 'zef_update_options;';
zef.h_as_opt_3.ValueChangedFcn = 'zef_update_options;';
zef.h_as_opt_4.ValueChangedFcn = 'zef_update_options;';
zef.h_meshing_threshold.ValueChangedFcn = 'zef_update_options;';
zef.h_as_opt_5.ValueChangedFcn = 'zef_update_options;';
zef.h_as_opt_6.ValueChangedFcn = 'zef_update_options;';
zef.h_cp2_on.ValueChangedFcn = 'zef_update_options;';
zef.h_cp2_a.ValueChangedFcn = 'zef_update_options;';
zef.h_cp3_on.ValueChangedFcn = 'zef_update_options;';
zef.h_use_depth_electrodes.ValueChangedFcn = 'zef_update_options;';
zef.h_source_model.ValueChangedFcn = 'zef_update_options;';
zef.h_colortune_param.ValueChangedFcn = 'zef_update_options;';
zef.h_inv_hyperprior_weight.ValueChangedFcn = 'zef_update_options;';
zef.h_cp_mode.ValueChangedFcn = 'zef_update_options;';
zef.h_brain_transparency.ValueChangedFcn = 'zef_update_options;';
zef.h_layer_transparency.ValueChangedFcn = 'zef_update_options;';
zef.h_inv_dynamic_range.ValueChangedFcn = 'zef_update_options;';
zef.h_inv_scale.ValueChangedFcn = 'zef_update_options;';
zef.h_inv_colormap.ValueChangedFcn = 'zef_update_options;';
zef.h_frame_start.ValueChangedFcn = 'zef_update_options;';
zef.h_frame_stop.ValueChangedFcn = 'zef_update_options;';
zef.h_frame_step.ValueChangedFcn = 'zef_update_options;';
zef.h_orbit_1.ValueChangedFcn = 'zef_update_options;';
zef.h_orbit_2.ValueChangedFcn = 'zef_update_options;';
zef.h_reconstruction_type.ValueChangedFcn = 'zef_update_options;';
zef.h_use_gpu.ValueChangedFcn = 'zef_update_options;';
zef.h_parcellation_type.ValueChangedFcn = 'zef_update_options;';
zef.h_gpu_num.ValueChangedFcn = 'zef_update_options;';
zef.h_parcellation_quantile.ValueChangedFcn = 'zef_update_options;';
zef.h_submesh_num.ValueChangedFcn = 'zef_update_options;';
zef.h_inv_hyperprior.ValueChangedFcn = 'zef_update_options;';
zef.h_inv_hyperprior_tail_length_db.ValueChangedFcn = 'zef_update_options;';
zef.h_cp2_b.ValueChangedFcn = 'zef_update_options;';
zef.h_cp2_c.ValueChangedFcn = 'zef_update_options;';
zef.h_cp2_d.ValueChangedFcn = 'zef_update_options;';
zef.h_cp3_a.ValueChangedFcn = 'zef_update_options;';
zef.h_cp3_b.ValueChangedFcn = 'zef_update_options;';
zef.h_cp3_c.ValueChangedFcn = 'zef_update_options;';
zef.h_cp3_d.ValueChangedFcn = 'zef_update_options;';

clear zef_data;

zef.h_inv_dynamic_range.Value = num2str(zef.inv_dynamic_range);
zef.h_orbit_1.Value = num2str(zef.orbit_1);
zef.h_orbit_2.Value = num2str(zef.orbit_2);
zef.h_meshing_threshold.Value = num2str(zef.meshing_threshold);
zef.h_brain_transparency.Value = num2str(zef.brain_transparency);
zef.h_layer_transparency.Value = num2str(zef.layer_transparency);
zef.h_frame_start.Value = num2str(zef.frame_start);
zef.h_frame_stop.Value = num2str(zef.frame_stop);
zef.h_frame_step.Value = num2str(zef.frame_step);
zef.h_submesh_num.Value = num2str(zef.submesh_num);
zef.h_reconstruction_type.ItemsData = [1:length(zef.h_reconstruction_type.Items)];
zef.h_reconstruction_type.Value = zef.reconstruction_type;
zef.h_parcellation_type.ItemsData = [1:length(zef.h_parcellation_type.Items)];
zef.h_parcellation_type.Value = zef.parcellation_type;
zef.h_parcellation_quantile.Value = num2str(zef.parcellation_quantile);
zef.h_use_depth_electrodes.Value = zef.use_depth_electrodes;
zef.h_source_model.ItemsData = [1:length(zef.h_source_model.Items)];
zef.h_source_model.Value = zef.source_model;
zef.h_use_gpu.Value = zef.use_gpu;
zef.h_gpu_num.Value = num2str(zef.gpu_num);
zef.h_as_opt_1.ItemsData = [1:length(zef.h_as_opt_1.Items)];
zef.h_as_opt_1.Value = zef.preconditioner; 
zef.h_as_opt_2.Value = num2str(zef.preconditioner_tolerance); 
zef.h_as_opt_3.Value = num2str(zef.smoothing_steps_surf); 
zef.h_as_opt_4.Value = num2str(zef.smoothing_steps_vol);
zef.h_as_opt_5.ItemsData = [1:length(zef.h_as_opt_5.Items)];
zef.h_as_opt_5.Value = zef.refinement_type;
zef.h_as_opt_6.Value = zef.surface_sources;
zef.h_cp2_on.Value = zef.cp2_on;
zef.h_cp_mode.ItemsData = [1:length(zef.h_cp_mode.Items)];
zef.h_cp_mode.Value = zef.cp_mode;
zef.h_cp2_a.Value = num2str(zef.cp2_a);
zef.h_cp2_b.Value = num2str(zef.cp2_b);
zef.h_cp2_c.Value = num2str(zef.cp2_c);
zef.h_cp2_d.Value = num2str(zef.cp2_d);
zef.h_cp3_on.Value = zef.cp3_on;
zef.h_cp3_a.Value = num2str(zef.cp3_a);
zef.h_cp3_b.Value = num2str(zef.cp3_b);
zef.h_cp3_c.Value = num2str(zef.cp3_c);
zef.h_cp3_d.Value = num2str(zef.cp3_d);
zef.h_inv_hyperprior_tail_length_db.Value = num2str(zef.inv_hyperprior_tail_length_db);
zef.h_colortune_param.Value = num2str(zef.colortune_param);
zef.h_as_opt_6.Value = zef.surface_sources;
zef.h_inv_hyperprior.ItemsData = [1:length(zef.h_inv_hyperprior.Items)];
zef.h_inv_hyperprior.Value = zef.inv_hyperprior;
zef.h_inv_hyperprior_weight.ItemsData = [1:length(zef.h_inv_hyperprior_weight.Items)];
zef.h_inv_hyperprior_weight.Value = zef.inv_hyperprior_weight;

zef.h_additional_options.Name = 'ZEFFIRO Interface: Options';
set(findobj(zef.h_additional_options.Children,'-property','FontUnits'),'FontUnits','pixels');
set(findobj(zef.h_additional_options.Children,'-property','FontSize'), 'FontSize', zef.font_size);

if zef.cp2_on
    zef.h_cp2_a.Enable = 'on';
    zef.h_cp2_b.Enable = 'on';
    zef.h_cp2_c.Enable = 'on';
    zef.h_cp2_d.Enable = 'on';
else
    zef.h_cp2_a.Enable = 'off';
    zef.h_cp2_b.Enable = 'off';
    zef.h_cp2_c.Enable = 'off';
    zef.h_cp2_d.Enable = 'off';
end

if zef.cp3_on
zef.h_cp3_a.Enable = 'on';
zef.h_cp3_b.Enable = 'on';
zef.h_cp3_c.Enable = 'on';
zef.h_cp3_d.Enable = 'on';
else
zef.h_cp3_a.Enable = 'off';
zef.h_cp3_b.Enable = 'off';
zef.h_cp3_c.Enable = 'off';
zef.h_cp3_d.Enable = 'off';
end

