examples.studies.decision_making.zef_parameters_focal_epilepsy;
[z_inverse_results, z_inverse_info] = zef_dataBank_get_reconstructions(zef,frame_number);
examples.studies.decision_making.zef_cluster_reconstructions_focal_epilepsy;
examples.studies.decision_making.zef_final_reconstruction_focal_epilepsy;
examples.studies.decision_making.zef_show_results_focal_epilepsy;
