function [mag_fig, rdm_fig] = eccentricity_diff_fig_fn( ...
    source_points, ...
    mags, ...
    rdms, ...
    legend_labels, ...
    n_intervals, ...
    x_scale, ...
    min_ecc, ...
    mag_handle_num, ...
    rdm_handle_num ...
)
[mag_fig, rdm_fig] = eccentricity_diff_fig_fn( ...
    source_points, ...
    mags, ...
    rdms, ...
    legend_labels, ...
    n_intervals, ...
    x_scale, ...
    min_ecc, ...
    mag_handle_num, ...
    rdm_handle_num ...
);
end