function [stensil, signs, source_moments, source_directions, source_locations, n_of_adj_nodes] = zef_ew_dipoles( ...
    nodes       ...
    ,               ...
    tetrahedra  ...
    ,               ...
    brain_ind   ...
    )
[stensil, signs, source_moments, source_directions, source_locations, n_of_adj_nodes] = zef_ew_dipoles( ...
    nodes       ...
    ,               ...
    tetrahedra  ...
    ,               ...
    brain_ind   ...
    );
end