function out_reduced_interpolation_matrix = zef_kron_reduction( ...
    in_interpolation_matrix, ...
    in_schur_complement, ...
    in_electrode_model, ...
    in_source_model ...
    )
out_reduced_interpolation_matrix = zef_kron_reduction( ...
    in_interpolation_matrix, ...
    in_schur_complement, ...
    in_electrode_model, ...
    in_source_model ...
    );
end