function [L_meg, dipole_locations, dipole_directions] = lead_field_meg_grad_fem( ...
    zef, ...
    nodes, ...
    elements, ...
    sigma, ...
    sensors, ...
    p_nearest_neighbour_inds, ...
    varargin ...
    )
[L_meg, dipole_locations, dipole_directions] = lead_field_meg_grad_fem( ...
    zef, ...
    nodes, ...
    elements, ...
    sigma, ...
    sensors, ...
    p_nearest_neighbour_inds, ...
    varargin ...
    );
end