function [G, dipole_locations] =  zef_lead_field_interpolation( ...
    p_nodes, ...
    p_tetrahedra, ...
    p_brain_inds, ...
    p_source_model, ...
    p_intended_source_inds, ...
    p_regparam ...
)
[G, dipole_locations] =  zef_lead_field_interpolation( ...
    p_nodes, ...
    p_tetrahedra, ...
    p_brain_inds, ...
    p_source_model, ...
    p_intended_source_inds, ...
    p_regparam ...
);
end