function [G, interpolation_positions] = zef_whitney_interpolation( ...
    p_nodes, ...
    p_tetrahedra, ...
    p_brain_inds, ...
    p_intended_source_inds ...
)
[G, interpolation_positions] = zef_whitney_interpolation( ...
    p_nodes, ...
    p_tetrahedra, ...
    p_brain_inds, ...
    p_intended_source_inds ...
);
end