function [T, Schur_complement, A] = zef_transfer_matrix( ...
    A                                                    ...
,                                                        ...
    B                                                    ...
,                                                        ...
    C                                                    ...
,                                                        ...
    n_of_fem_nodes                                       ...
,                                                        ...
    n_of_electrodes                                      ...
,                                                        ...
    electrode_model                                      ...
,                                                        ...
    permutation                                          ...
,                                                        ...
    precond                                              ...
,                                                        ...
    impedance_vec                                        ...
,                                                        ...
    impedance_inf                                        ...
,                                                        ...
    tol_val                                              ...
,                                                        ...
    m_max                                                ...
,                                                        ...
    schur_expression                                     ...
)
[T, Schur_complement, A] = zef_transfer_matrix( ...
    A                                                    ...
,                                                        ...
    B                                                    ...
,                                                        ...
    C                                                    ...
,                                                        ...
    n_of_fem_nodes                                       ...
,                                                        ...
    n_of_electrodes                                      ...
,                                                        ...
    electrode_model                                      ...
,                                                        ...
    permutation                                          ...
,                                                        ...
    precond                                              ...
,                                                        ...
    impedance_vec                                        ...
,                                                        ...
    impedance_inf                                        ...
,                                                        ...
    tol_val                                              ...
,                                                        ...
    m_max                                                ...
,                                                        ...
    schur_expression                                     ...
);
end