function output_struct = sensitivity_data_from_structs_fn(folder, file_pattern)

    % sensitivity_data_from_structs_fn
    %
    % Loads the sensitivity data from structs generated by
    % inverse_sensitivity_fn and saved into .mat files and returns it in an
    % output struct.
    %
    % Input
    %
    % - folder
    %
    %   The folder in which the files are located.
    %
    % - file_pattern
    %
    %   A textual pattern that this function uses to load a specific set of
    %   files. Support the same regular expressions or glob patterns as the
    %   Matlab function dir.
    %
    % Output
    %
    % - output_struct
    %
    %   The inverse sensitivity data loaded into a single struct of structs.
    %

    arguments

        folder (1,1) string

        file_pattern (1,1) string

    end

    % Initialize empty output.

    output_struct = struct;

    file_path_pattern = fullfile(folder, file_pattern);

    file_info = dir(file_path_pattern);

    for i = 1 : numel(file_info)

        file_path = fullfile(folder, file_info(i).name);

        [fpath, fname, fextension] = fileparts(file_path);

        file_contents = load(file_path);

        contents_is_struct = isstruct(file_contents);

        if contents_is_struct

            output_struct = collect_data_from(fname, file_contents, output_struct);

        else

            warning("We do not support non-struct file contents. Skipping…")

        end

    end

end % function


function output_struct = collect_data_from(fname, file_contents, output_struct)

    %
    % collect_data_from(file_contents)
    %
    % A helper function for generating a struct of structs of measurement data
    % generated by the inverse_sensitivity_fn.
    %
    % Input
    %
    % - fname
    %
    %   The name of the file file_contents was loaded from, without the suffix
    %   or path. Must be a valid Matlab identifier.
    %
    % - file_contents
    %
    %   File contents loaded from a .mat file.
    %
    % - output_struct
    %
    %   The struct that this function modifies and the returns, with data from
    %   file contens added into it.
    %
    % Output:
    %
    % - output_struct
    %
    %   What the input documentation on output_struct says.
    %

    arguments

        fname (1,1) string

        file_contents (1,1) struct

        output_struct (1,1) struct

    end

    if strlength(fname) == 0

        error("I was given an empty file name. Cannot generate a result compilation struct.")

    end

    field_names = fieldnames(file_contents);

    for i = 1 : numel(field_names)

        field_name = field_names{i};

        data = file_contents.(field_name);

        % Check that the struct contains the fields expected from data generated
        % by inverse_sensitivity_fn, or that.

        if isstruct(data) ...
        && isfield(data, "dist_vec") ...
        && isfield(data, "angle_vec") ...
        && isfield(data, "mag_vec") ...
        && isfield(data, "dist_vec_avg") ...
        && isfield(data, "angle_vec_avg") ...
        && isfield(data, "mag_vec_avg") ...
        && isfield(data, "dist_vec_std") ...
        && isfield(data, "angle_vec_std") ...
        && isfield(data, "mag_vec_std")

            output_struct.(fname).results = data;

        elseif isa(data, "double") && numel(size(data)) == 2 && field_name == "L"

            output_struct.(fname).L = data;

        else

            warning("Data struct is not a struct or does not contain fields produced by inverse_sensitivity_fn. Skipping…")

            continue

        end

    end

end % function
