function [meshStruct,tissueTable] = main(meshFile, tissueListingFile, kwargs)
%
% [meshStruct, tissueTable] = utilities.simnibsToZef.main(meshFile, tissueListingFile, kwargs)
%
% Loads a mesh and a related tissue data table from a set of given  mesh file and
% a tissue listing file generated by the charm pipeline of SimNIBS. Also stores
% these on disk if asked to do so via a non-empty output folder path.
%
% Inputs:
%
%   meshFile (1,1) string { mustBeFile }
%
% A file containing the nodes, triangles, tetrahedra and the labels of these elements.
% This should be generated by SimNIBS.
%
%   tissueListingFile (1,1) string { mustBeFile }
%
% SimNIBS also generates a table of tissue labels, their names and color codes.
% This path should point to it.
%
%   kwargs.outputFolder (1,1) string = ""
%
% If given as a non-empty string, the separate compartments are saved to separate STL files (in the case of triangles)
% and MAT files in the case of tetrahedra.
%
%   kwargs.dateTimeFormat (1,1) string = "yyyy-MM-dd-HH-mm-ss-SSS"
%
% A datetime of the result generation is automatically included into the output file names.
% The datetime will follow this format.
%
%   kwargs.labelNameStr (1,1) string = "Label_Name:"
%
% The intended column name of the tissuTable column containing the compartment names.
%
%   kwargs.labelStr (1,1) string = "#No."
%
% The name of the number label column of the tissueTable column containing the compartment labels.
%
%   kwargs.stlOutputFormat (1,1) string { mustBeMember(kwargs.stlOutputFormat, ["text", "binary"]) } = "binary"
%
% The output format of the output surface triangulations. Binary is more compact, but slightly harder to parse
% than the text (ASCII) form of STL files.
%

    arguments
        meshFile (1,1) string { mustBeFile }
        tissueListingFile (1,1) string { mustBeFile }
        kwargs.outputFolder (1,1) string = ""
        kwargs.dateTimeFormat (1,1) string = "yyyy-MM-dd-HH-mm-ss-SSS"
        kwargs.labelNameStr (1,1) string = "Label_Name:"
        kwargs.labelStr (1,1) string = "#No."
        kwargs.stlOutputFormat (1,1) string { mustBeMember(kwargs.stlOutputFormat, ["text", "binary"]) } = "binary"
    end % arguments

    % Save start time.

    dateTime = datetime("now", Format=kwargs.dateTimeFormat) ;

    dateTimeStr = string(dateTime)

    % Load mesh from SimNIBS-generated .msh file.

    meshStruct = utilities.simnibsToZef.meshLoadGmsh4(meshFile)

    % Load tissue labels and names from tissue listing file.

    tissueTable = readtable(tissueListingFile, CommentStyle='#', WhiteSpace=" \t") ;

    tissueFileLines = readlines(tissueListingFile) ;

    headerRowStr = "" ;

    for ii = 1 : numel(tissueFileLines)

        line = tissueFileLines(ii) ;

        if startsWith(line, "#")

            headerRowStr = line ;

            break

        end % if

    end % for

    headerRowStrings = split(headerRowStr) ;

    if numel(headerRowStrings) > size(tissueTable,2) && headerRowStrings(2) ~= kwargs.labelNameStr

        % We might have the second column name in the tissue file contain a space, meaning it needs to be merged.

        headerRowStrings(2) = strjoin([headerRowStrings(2), headerRowStrings(3)], "_") ;

        headerRowStrings(3 : 6) = headerRowStrings(4:end) ;

        headerRowStrings(end) = [] ;

    end

    tissueTable.Properties.VariableNames = headerRowStrings ;

    if ismember(kwargs.labelNameStr, tissueTable.Properties.VariableNames)

        tissueTable = convertvars(tissueTable, kwargs.labelNameStr, "string") ;

    end % if

    % Go over tissues and save the data to separate STL files.

    if strlength(strtrim(kwargs.outputFolder)) > 0

        writeToFiles = true ;

        if ~ isfolder(kwargs.outputFolder)

            warning("The given input path (" + kwargs.outputFolder + ") did not point to an existing folder. Not saving results to it.") ;

            writeToFiles = false ;

        end % if

        tissueLabels = tissueTable.(kwargs.labelStr) ;

        tissueNames = tissueTable.(kwargs.labelNameStr) ;

        meshNodes = meshStruct.nodes ;

        meshTriangles = meshStruct.triangles ;

        meshTetra = meshStruct.tetrahedra ;

        meshTriangleLabels = meshStruct.triangle_regions ;

        meshTetraLabels = meshStruct.tetrahedron_regions ;

        nodeRange = 1 : size(meshNodes,1) ;

        for ii = 1 : numel(tissueLabels)

            if ~ writeToFiles

                break

            end

            triangleLabel = tissueLabels(ii) + 1000 ; % Don't ask why this 1000 is here. It's just how it is encoded.

            tetraLabel = tissueLabels(ii) ;

            name = tissueNames(ii) ;

            triangleMask = meshTriangleLabels == triangleLabel ;

            if any(triangleMask)

                trianglePath = fullfile(kwargs.outputFolder, name + "." + dateTimeStr + ".triangles.stl") ;

                display("Writing triangles of " + name + " to " + trianglePath) ;

                relevantTriangles = meshTriangles(triangleMask,:) ;

                relevantTriangleNodes = meshNodes ; % TODO: make this reference only relevant nodes.

                triangleTriangulation = triangulation(double(relevantTriangles), relevantTriangleNodes) ;

                stlwrite(triangleTriangulation, trianglePath, kwargs.stlOutputFormat)

            else

                warning("The compartment " + name + " did not contain any triangles. Not generating file.") ;

            end % if

            tetraMask = meshTetraLabels == tetraLabel ;

            if any(tetraMask)

                tetraPath = fullfile(kwargs.outputFolder, name + "." + dateTimeStr + ".tetra.mat") ;

                display("Writing tetra of " + name + " to " + tetraPath) ;

                tetraFile = matfile(tetraPath, Writable=true) ;

                relevantTetra = meshTetra(tetraMask,:) ;

                relevantTetraNodes = meshNodes ; % TODO: make this reference only relevant nodes.

                tetraTriangulation = triangulation(double(relevantTetra), meshNodes) ;

                tetraFile.nodes = relevantTetraNodes ;

                tetraFile.tetra = relevantTetra ;

            else

                warning("The compartment " + name + " did not contain any tetrahedra. Not generating file.") ;

            end % if

        end % for

    end % if

end % function
