
    % --- Simulate (delay-free, looped passes) ---
    zef.source_tree_simulated = zef_simulate_jr_tree( ...
        zef.source_tree, ...
        zef.source_tree_signal_parameters );

    % --- Publish with delays (pure time translation only) ---
    zef.source_tree_published = zef_publish_jr_tree_delays( ...
        zef.source_tree_simulated, ...
        zef.source_tree, ...
        zef.source_tree_signal_parameters );

