function sensitivities_with_statistics = inverse_sensitivity_fn( ...
    project_path, ...
    inverse_method, ...
    n_of_runs, ...
    noise_level_db, ...
    diff_type, ...
    args ...
)
sensitivities_with_statistics = inverse_sensitivity_fn( ...
    project_path, ...
    inverse_method, ...
    n_of_runs, ...
    noise_level_db, ...
    diff_type, ...
    args ...
);
end