function compartmentDataTable = readAsegStatsFile(asegFilePath, kwargs)
%
% compartmentDataTable = readAsegStatsFile(asegFilePath, kwargs)
%
% Reads an aseg.stats file for brain compartment statistics table.
% These are related to a corresponding aseg.mgz file with the actual compartment data.
% Both of these files should be generated by the recon-all binary
% of the FreeSurfer software suite.
%

    arguments
        asegFilePath (1,1) string { mustBeFile }
        kwargs.headerRowPrefix (1,1) string = "# ColHeaders"
        kwargs.rowNPrefix (1,1) string = "# NRows"
        kwargs.columnNPrefix (1,1) string = "# NTableCols"
        kwargs.statsFileCommentStyle (1,1) string = "#"
        kwargs.compartmentNameColumnTitle (1,1) string = "StructName"
    end

    if ~ endsWith(asegFilePath, ".stats")

        warning("The given path " + asegFilePath + " did not have the .stats suffix. Are you sure this is the right file?")

    end % if

    % First we simply read the file into a MATLAB table.

    compartmentDataTable = readtable(asegFilePath, FileType="text", CommentStyle=kwargs.statsFileCommentStyle) ;

    % Then we read the commented lines at the start of the stats file to figure out the table headers.

    statsFileLines = readlines(asegFilePath, EmptyLineRule="skip", WhiteSpaceRule="trim") ;

    lineN = numel(statsFileLines) ;

    columnN = 0 ;

    rowN = 0 ;

    for ii = 1 : lineN

        line = statsFileLines(ii) ;

        if ~ startsWith(line, "#")

            break

        end % if

        if startsWith(line, kwargs.columnNPrefix)

            splitLine = split(line) ;

            columnN = double(splitLine(end))

        end % if

        if startsWith(line, kwargs.rowNPrefix)

            splitLine = split(line) ;

            rowN = double(splitLine(end)) ;

        end % if

        if startsWith(line, kwargs.headerRowPrefix)

            tableHeaders = split(line) ;

            compartmentDataTable.Properties.VariableNames = tableHeaders(end - columnN + 1 : end) ;

            break

        end

    end % for

    if ismember(kwargs.compartmentNameColumnTitle, compartmentDataTable.Properties.VariableNames)

        compartmentDataTable = convertvars(compartmentDataTable, kwargs.compartmentNameColumnTitle, "string")

    end % if

end % function
