function h1 = exp_em_map_estimation_multires_kopio()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
% 
% To reopen this object, just type the name of the MATLAB file at the MATLAB
% prompt. The MATLAB code file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the MATLAB code file/MAT-file format, and should be saved as
% FIG-files.



appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'axes', 3, ...
    'text', 36, ...
    'pushbutton', 16, ...
    'popupmenu', 9, ...
    'edit', 24, ...
    'checkbox', 3), ...
    'override', 1, ...
    'release', 13, ...
    'resize', 'simple', ...
    'accessibility', 'callback', ...
    'mfile', 0, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'template', 'C:\Program Files\MATLAB\R2010a\toolbox\matlab\guide\guitemplates\guidetemplate0.fig', ...
    'lastFilename', 'C:\Users\joona\Documents\MATLAB\zeffiro_interface-master\plugins\exp_em_multires\fig\exp_em_map_estimation_multires_kopio.fig');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Units','normalized',...
'Position',[0.4325 0.360826210826211 0.184895833333333 0.664814814814815],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',get(0,'defaultfigureColor'),...
'CloseRequestFcn',get(0,'defaultfigureCloseRequestFcn'),...
'CurrentAxesMode','manual',...
'CurrentObjectMode','manual',...
'CurrentPointMode','manual',...
'SelectionTypeMode','manual',...
'ResizeFcn',blanks(0),...
'IntegerHandle','off',...
'NextPlot',get(0,'defaultfigureNextPlot'),...
'Alphamap',get(0,'defaultfigureAlphamap'),...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'WindowButtonDownFcn',blanks(0),...
'WindowButtonUpFcn',blanks(0),...
'WindowButtonMotionFcn',blanks(0),...
'WindowScrollWheelFcn',blanks(0),...
'WindowKeyPressFcn',blanks(0),...
'WindowKeyReleaseFcn',blanks(0),...
'MenuBar','none',...
'ToolBar','none',...
'Pointer',get(0,'defaultfigurePointer'),...
'PointerShapeHotSpot',get(0,'defaultfigurePointerShapeHotSpot'),...
'Name','IAS MAP estimation multiresolution',...
'NumberTitle','off',...
'HandleVisibility','off',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','figure1',...
'UserData',[],...
'WindowStyle',get(0,'defaultfigureWindowStyle'),...
'DockControls',get(0,'defaultfigureDockControls'),...
'Resize',get(0,'defaultfigureResize'),...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',[20.99999864 29.69999902],...
'PaperType',get(0,'defaultfigurePaperType'),...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'PaperOrientation',get(0,'defaultfigurePaperOrientation'),...
'ScreenPixelsPerInchMode','manual',...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'text2';

h2 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','q parameter:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[13.411186696901 550.820320855615 166.476190476191 18.6866310160428],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text2',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_q';

h3 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','normalized',...
'String',{  '1'; '2' },...
'Style','popupmenu',...
'Value',1,...
'Position',[201.586545729403 546.148663101604 142.69387755102 26.8620320855615],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_q = get(gcbo,''Value'');',...
'Children',[],...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_q = gcbo;', appdata} ,...
'Tag','h_exp_em_multires_q',...
'UserData',[],...
'FontSize',0.330249768732655);

appdata = [];
appdata.lastValidTag = 'text3';

h4 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Shape parameter:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[13.411186696901 513.447058823529 166.476190476191 18.6866310160428],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text3',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text4';

h5 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Scaling parameter:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[13.411186696901 481.913368983957 166.476190476191 18.6866310160428],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text4',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_beta';

h6 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','1.5',...
'Style','edit',...
'Value',1,...
'Position',[277.084656084656 512.279144385027 63.0748299319728 21.0224598930481],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_beta = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_beta = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_beta',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_theta0';

h7 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','0.001',...
'Style','edit',...
'Value',1,...
'Position',[277.084656084656 480.745454545455 63.0748299319728 21.0224598930482],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_theta0 = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_theta0 = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_theta0',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text6';

h8 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','IAS MAP iterations:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[13.411186696901 420.013903743315 166.476190476191 18.6866310160428],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text6',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_n_iter';

h9 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','25',...
'Style','edit',...
'Value',1,...
'Position',[277.084656084656 418.845989304813 63.0748299319728 21.0224598930482],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_n_iter = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_n_iter = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_n_iter',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text10';

h10 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Sampling frequency (Hz):',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0349939474536682 0.493761140819964 0.469387755102041 0.0285204991087344],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text10',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_sampling_frequency';

h11 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','1025',...
'Style','edit',...
'Value',1,...
'Position',[0.77843418068982 0.491978609625668 0.177842565597668 0.0320855614973262],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_sampling_frequency = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_sampling_frequency = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_sampling_frequency',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text11';

h12 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Low-cut frequency (Hz):',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0349939474536682 0.443850267379679 0.469387755102041 0.0285204991087343],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text11',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394585,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_low_cut_frequency';

h13 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','7',...
'Style','edit',...
'Value',1,...
'Position',[0.77843418068982 0.442067736185383 0.177842565597668 0.0320855614973262],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_low_cut_frequency = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_low_cut_frequency = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_low_cut_frequency',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394585,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text12';

h14 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','High-cut frequency (Hz):',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0349939474536682 0.39572192513369 0.469387755102041 0.0285204991087343],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text12',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394581,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_high_cut_frequency';

h15 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','9',...
'Style','edit',...
'Value',1,...
'Position',[0.77843418068982 0.392156862745098 0.177842565597668 0.0320855614973262],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_high_cut_frequency = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_high_cut_frequency = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_high_cut_frequency',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394585,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_start';

h16 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Start',...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.408171790019266 0.0213903743315508 0.169096209912537 0.0454755989725883],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback','zef_update_exp_em_multires; zef.reconstruction = exp_em_iteration_multires([]);',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_start = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_start',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_cancel';

h17 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Close',...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0466557550338431 0.0213903743315508 0.169096209912536 0.0454755989725883],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback','close(zef.h_exp_em_map_estimation_multires);',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_cancel = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_cancel',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text19';

h18 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Number of time steps:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0349939474536682 0.24777183600713 0.469387755102041 0.0285204991087344],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text19',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_number_of_frames';

h19 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','1',...
'Style','edit',...
'Value',1,...
'Position',[0.77843418068982 0.244206773618538 0.177842565597668 0.0320855614973262],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_number_of_frames = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_number_of_frames = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_number_of_frames',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394585,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text20';

h20 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Likelihood STD:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[13.411186696901 450.379679144385 166.476190476191 18.6866310160428],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text20',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394587,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_likelihood_std';

h21 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','0.05',...
'Style','edit',...
'Value',1,...
'Position',[277.084656084656 449.211764705882 63.0748299319728 21.0224598930482],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_likelihood_std = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_likelihood_std = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_likelihood_std',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_apply';

h22 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Apply',...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.227413772526555 0.0213903743315508 0.169096209912537 0.0454755989725883],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback','zef_update_exp_em_multires;',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_apply = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_apply',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text25';

h23 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Data normalization:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0349939474536682 0.0944741532976827 0.469387755102041 0.0285204991087344],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text25',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394587,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_normalize_data';

h24 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','normalized',...
'String',{  'Maximum entry'; 'Maximum column norm'; 'Average column norm'; 'None' },...
'Style','popupmenu',...
'Value',1,...
'Position',[0.565589142925341 0.089126559714795 0.402332361516035 0.0409982174688057],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_normalize_data = get(gcbo,''value'');',...
'Children',[],...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_normalize_data = gcbo;', appdata} ,...
'Tag','h_exp_em_multires_normalize_data',...
'UserData',[],...
'FontSize',0.330249768732655);

appdata = [];
appdata.lastValidTag = 'text26';

h25 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Time interval start (s):',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0349939474536682 0.345811051693405 0.469387755102041 0.0285204991087344],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text26',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_time_1';

h26 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','0',...
'Style','edit',...
'Value',1,...
'Position',[0.77843418068982 0.344028520499109 0.177842565597668 0.0320855614973262],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_time_1 = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_time_1 = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_time_1',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394585,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text27';

h27 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Time window (s):',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0349939474536682 0.295900178253119 0.469387755102041 0.0285204991087344],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text27',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_time_2';

h28 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','0',...
'Style','edit',...
'Value',1,...
'Position',[0.77843418068982 0.294117647058824 0.177842565597668 0.0320855614973262],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_time_2 = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_time_2= gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_time_2',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394585,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text30';

h29 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Data segment:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0349939474536682 0.14795008912656 0.469387755102041 0.0285204991087344],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text30',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394581,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_data_segment';

h30 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','1',...
'Style','edit',...
'Value',1,...
'Position',[0.77843418068982 0.146167557932264 0.177842565597668 0.0320855614973262],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_data_segment = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_data_segment = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_data_segment',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394585,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text31';

h31 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Time step (s):',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0349939474536682 0.197860962566845 0.469387755102041 0.0285204991087344],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text31',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_time_3';

h32 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','0',...
'Style','edit',...
'Value',1,...
'Position',[0.77843418068982 0.196078431372549 0.177842565597668 0.0320855614973262],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_time_3 = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_time_3= gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_time_3',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394585,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text32';

h33 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Multiresolution levels:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[14.4452003023432 689.802139037433 166.476190476191 18.6866310160428],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text32',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394587,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text33';

h34 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Multiresolution sparsity:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[14.4452003023432 658.268449197861 166.476190476191 18.6866310160428],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text33',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394583,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_n_levels';

h35 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','1.5',...
'Style','edit',...
'Value',1,...
'Position',[278.118669690098 688.63422459893 63.0748299319728 21.0224598930481],...
'BackgroundColor',[1 1 1],...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_n_levels = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_n_levels',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394582,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_sparsity';

h36 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','0.001',...
'Style','edit',...
'Value',1,...
'Position',[278.118669690098 657.100534759358 63.0748299319728 21.0224598930481],...
'BackgroundColor',[1 1 1],...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_sparsity = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_sparsity',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394582,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_make_multires_dec';

h37 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Create multiresolution decomposition',...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[135.427815570673 584.689839572192 206.802721088435 29.7956124468399],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback','zef_update_exp_em_multires; [zef.exp_em_multires_dec, zef.exp_em_multires_ind, zef.exp_em_multires_count] = exp_em_make_multires_dec;',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_make_multires_dec = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_make_multires_dec',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text34';

h38 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Number of decompositions:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[14.4452003023432 626.734759358289 166.476190476191 18.6866310160428],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text34',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394587,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_n_decompositions';

h39 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','10',...
'Style','edit',...
'Value',1,...
'Position',[278.118669690098 625.566844919786 63.0748299319728 21.0224598930481],...
'BackgroundColor',[1 1 1],...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_n_decompositions = gcbo;', appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','h_exp_em_multires_n_decompositions',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8.87117988394582,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text35';

h40 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','L1 iterations:',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[13 389 166 19],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text35',...
'UserData',[],...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'h_exp_em_multires_n_L1_iterations';

h41 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits','pixels',...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','5',...
'Style','edit',...
'Value',1,...
'Position',[277 388 63 21],...
'BackgroundColor',[1 1 1],...
'Callback','zef.exp_em_multires_n_L1_iterations = str2num(get(gcbo,''string''));',...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'CreateFcn', {@local_CreateFcn, 'zef.h_exp_em_multires_n_L1_iterations = gcbo;', appdata} ,...
'Tag','h_exp_em_multires_n_L1_iterations',...
'UserData',[],...
'FontSize',8.87117988394584,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));



% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end
