classdef MeshVisualizationTool < handle

    % MeshVisualizationTool
    %
    % A tool for visualizing finite element meshed generated by Zeffiro
    % Interface.

    properties

        zef app.Zef

        % Other properties here.

    end % properties

    methods

        function self = MeshVisualizationTool(zef, varargin)

            self.zef = zef;

        end

    end % methods

end % MeshVisualizationTool
