classdef MeshVisualizationTool < handle

    % MeshVisualizationTool
    %
    % A tool for visualizing finite element meshed generated by Zeffiro
    % Interface.

    properties

        zef app.Zef

        tab matlab.ui.container.Tab

        layout matlab.ui.container.GridLayout

        % Button layout

        layoutrow1 matlab.ui.container.GridLayout

        volume_button matlab.ui.control.Button

        surfaces_button matlab.ui.control.Button

        movie_button matlab.ui.control.Button

        popup_button matlab.ui.control.Button

        graph_button matlab.ui.control.Button

        % Tickboxes and dropdowns + labels

        layoutrow2 matlab.ui.container.GridLayout

        att_electr_cb matlab.ui.control.CheckBox

        infl_surf_cb matlab.ui.control.CheckBox

        cone_field_cb matlab.ui.control.CheckBox

        streamlines_cb matlab.ui.control.CheckBox

        contourlabels_cb matlab.ui.control.CheckBox

        clip_plane_1_cb matlab.ui.control.CheckBox

        clip_plane_2_cb matlab.ui.control.CheckBox

        clip_plane_3_cb matlab.ui.control.CheckBox

        axesbox_cb matlab.ui.control.CheckBox

        contour_array_cb matlab.ui.control.CheckBox

        % Dropdowns + labels

        layoutrow3 matlab.ui.container.GridLayout

        reconstype_lbl matlab.ui.control.Label

        reconsttype_dd matlab.ui.control.DropDown

        visualizationtype_lbl matlab.ui.control.Label

        visualizationtype_dd matlab.ui.control.DropDown

        cutplanemode_lbl matlab.ui.control.Label

        cutplanemode_dd matlab.ui.control.DropDown

        plotscale_lbl matlab.ui.control.Label

        plotscale_dd matlab.ui.control.DropDown

        distr_mode_lbl matlab.ui.control.Label

        distr_mode_dd matlab.ui.control.DropDown

        colormap_lbl matlab.ui.control.Label

        colormap_dd matlab.ui.control.DropDown

        parameter_lbl matlab.ui.control.Label

        parameter_dd matlab.ui.control.DropDown

        graph_lbl matlab.ui.control.Label

        graph_dd matlab.ui.control.DropDown

        % Editboxes

        layoutrow4 matlab.ui.container.GridLayout

        orientation_lbl matlab.ui.control.Label

        orientation_height_ef matlab.ui.control.EditField

        orientation_azimuth_ef matlab.ui.control.EditField

        rotspeed_lbl matlab.ui.control.Label

        rotspeed_height_ef matlab.ui.control.EditField

        rotspeed_azimuth_ef matlab.ui.control.EditField

        distance_lbl matlab.ui.control.Label

        distance_dist_ef matlab.ui.control.EditField

        distance_expl_ef matlab.ui.control.EditField

        transp_lbl matlab.ui.control.Label

        transp_rec_ef matlab.ui.control.EditField

        transp_surf_ef matlab.ui.control.EditField

        submesh_lbl matlab.ui.control.Label

        submesh1_ef matlab.ui.control.EditField

        submesh2_ef matlab.ui.control.EditField

        plot_thresh_lbl matlab.ui.control.Label

        plot_thresh_ef matlab.ui.control.EditField

        % More editboxes

        layoutrow5 matlab.ui.container.GridLayout

        frame_lbl matlab.ui.control.Label

        frame_start_ef matlab.ui.control.EditField

        frame_stop_ef matlab.ui.control.EditField

        frame_step_ef matlab.ui.control.EditField

        % Clipping plane settings

        layoutrow6 matlab.ui.container.GridLayout

        plane1label matlab.ui.control.Label

        plane1x_ef matlab.ui.control.EditField

        plane1y_ef matlab.ui.control.EditField

        plane1z_ef matlab.ui.control.EditField

        plane1range_ef matlab.ui.control.EditField

        plane2label matlab.ui.control.Label

        plane2x_ef matlab.ui.control.EditField

        plane2y_ef matlab.ui.control.EditField

        plane2z_ef matlab.ui.control.EditField

        plane2range_ef matlab.ui.control.EditField

        plane3label matlab.ui.control.Label

        plane3x_ef matlab.ui.control.EditField

        plane3y_ef matlab.ui.control.EditField

        plane3z_ef matlab.ui.control.EditField

        plane3range_ef matlab.ui.control.EditField

    end % properties

    methods

        function self = MeshVisualizationTool(zef, tabs, varargin)

            self.zef = zef;

            self.tab = uitab(tabs, 'Title', 'Mesh Visualization Tool');

            self.layout = uigridlayout(self.tab, [6,1], 'Scrollable', 'on');

            self.layout.ColumnWidth = { 'fit' };

            % Buttons

            self.layoutrow1 = uigridlayout(self.layout, [2,3]);

            self.volume_button = uibutton(self.layoutrow1, 'Text', 'Visualize volume');

            self.surfaces_button = uibutton(self.layoutrow1, 'Text', 'Visualize surfaces');

            self.movie_button = uibutton(self.layoutrow1, 'Text', 'Frame / Movie');

            self.popup_button = uibutton(self.layoutrow1, 'Text', 'Axes pop-up');

            self.graph_button = uibutton(self.layoutrow1, 'Text', 'Plot graph');

            % Tickboxes and dropdowns

            self.layoutrow2 = uigridlayout(self.layout, [2,5]);

            self.att_electr_cb = uicheckbox(self.layoutrow2, 'Text', 'Attach electrodes');

            self.infl_surf_cb = uicheckbox(self.layoutrow2, 'Text', 'Use inflated surfaces');

            self.cone_field_cb = uicheckbox(self.layoutrow2, 'Text', 'Cone field');

            self.streamlines_cb = uicheckbox(self.layoutrow2, 'Text', 'Streamlines');

            self.contourlabels_cb = uicheckbox(self.layoutrow2, 'Text', 'Contour labels');

            self.clip_plane_1_cb = uicheckbox(self.layoutrow2, 'Text', 'Clipping plane 1');

            self.clip_plane_2_cb = uicheckbox(self.layoutrow2, 'Text', 'Clipping plane 2');

            self.clip_plane_3_cb = uicheckbox(self.layoutrow2, 'Text', 'Clipping plane 3');

            self.axesbox_cb = uicheckbox(self.layoutrow2, 'Text', 'Axes box');

            self.contour_array_cb = uicheckbox(self.layoutrow2, 'Text', 'Contour array');

            % Dropdowns + labels

            self.layoutrow3 = uigridlayout(self.layout, [2,8]);

            self.reconstype_lbl = uilabel(self.layoutrow3, 'Text', 'Reconstruction type');

            self.reconsttype_dd = uidropdown(self.layoutrow3);

            self.visualizationtype_lbl = uilabel(self.layoutrow3, 'Text', 'Visualization type');

            self.visualizationtype_dd = uidropdown(self.layoutrow3);

            self.cutplanemode_lbl = uilabel(self.layoutrow3, 'Text', 'Cutting plane mode');

            self.cutplanemode_dd = uidropdown(self.layoutrow3);

            self.plotscale_lbl = uilabel(self.layoutrow3, 'Text', 'Plot scale');

            self.plotscale_dd = uidropdown(self.layoutrow3);

            self.distr_mode_lbl = uilabel(self.layoutrow3, 'Text', 'Distribution mode');

            self.distr_mode_dd = uidropdown(self.layoutrow3);

            self.colormap_lbl = uilabel(self.layoutrow3, 'Text', 'Color map');

            self.colormap_dd = uidropdown(self.layoutrow3);

            self.parameter_lbl = uilabel(self.layoutrow3, 'Text', 'Parameter');

            self.parameter_dd = uidropdown(self.layoutrow3);

            self.graph_lbl = uilabel(self.layoutrow3, 'Text', 'Graph type');

            self.graph_dd = uidropdown(self.layoutrow3);

            % Editboxes

            self.layoutrow4 = uigridlayout(self.layout, [3 6], 'Scrollable','on');

            self.orientation_lbl = uilabel(self.layoutrow4, 'Text', 'Orientation height / azimuth');

            self.orientation_height_ef = uieditfield(self.layoutrow4);

            self.orientation_azimuth_ef = uieditfield(self.layoutrow4);

            self.rotspeed_lbl = uilabel(self.layoutrow4, 'Text', 'Rotation speed height / azimuth');

            self.rotspeed_height_ef = uieditfield(self.layoutrow4);

            self.rotspeed_azimuth_ef = uieditfield(self.layoutrow4);

            self.distance_lbl = uilabel(self.layoutrow4, 'Text', 'Distance / Explode');

            self.distance_dist_ef = uieditfield(self.layoutrow4);

            self.distance_expl_ef = uieditfield(self.layoutrow4);

            self.transp_lbl = uilabel(self.layoutrow4, 'Text', 'Transparency rec. / surf.');

            self.transp_rec_ef = uieditfield(self.layoutrow4);

            self.transp_surf_ef = uieditfield(self.layoutrow4);

            self.submesh_lbl = uilabel(self.layoutrow4, 'Text', 'Submesh');

            self.submesh1_ef = uieditfield(self.layoutrow4);

            self.submesh2_ef = uieditfield(self.layoutrow4);

            self.plot_thresh_lbl = uilabel(self.layoutrow4, 'Text', 'Plot threshold');

            self.plot_thresh_ef = uieditfield(self.layoutrow4);

            % More editboxes

            self.layoutrow5 = uigridlayout(self.layout, [1 4]);

            self.frame_lbl = uilabel(self.layoutrow5, 'Text', 'Frame start / stop / step');

            self.frame_start_ef = uieditfield(self.layoutrow5);

            self.frame_stop_ef = uieditfield(self.layoutrow5);

            self.frame_step_ef = uieditfield(self.layoutrow5);

            % Clipping plane settings

            self.layoutrow6 = uigridlayout(self.layout, [3 5]);

            self.plane1label = uilabel(self.layoutrow6, 'Text', 'Clipping plane 1');

            self.plane1x_ef = uieditfield(self.layoutrow6);

            self.plane1y_ef = uieditfield(self.layoutrow6);

            self.plane1z_ef = uieditfield(self.layoutrow6);

            self.plane1range_ef = uieditfield(self.layoutrow6);

            self.plane2label = uilabel(self.layoutrow6, 'Text', 'Clipping plane 2');

            self.plane2x_ef = uieditfield(self.layoutrow6);

            self.plane2y_ef = uieditfield(self.layoutrow6);

            self.plane2z_ef = uieditfield(self.layoutrow6);

            self.plane2range_ef = uieditfield(self.layoutrow6);

            self.plane3label = uilabel(self.layoutrow6, 'Text', 'Clipping plane 3');

            self.plane3x_ef = uieditfield(self.layoutrow6);

            self.plane3y_ef = uieditfield(self.layoutrow6);

            self.plane3z_ef = uieditfield(self.layoutrow6);

            self.plane3range_ef = uieditfield(self.layoutrow6);

        end

    end % methods

end % MeshVisualizationTool
