classdef MeshVisualizationTool < handle

    % MeshVisualizationTool
    %
    % A tool for visualizing finite element meshed generated by Zeffiro
    % Interface.

    properties

        zef app.Zef

        tab matlab.ui.container.Tab

        layout matlab.ui.container.GridLayout

    end % properties

    methods

        function self = MeshVisualizationTool(zef, tabs, varargin)

            self.zef = zef;

            self.tab = uitab(tabs, 'Title', 'Mesh Visualization Tool');

            self.layout = uigridlayout(self.tab, [1,1]);

        end

    end % methods

end % MeshVisualizationTool
