function self = fromFreeSurferSegmentation ( self, segmentation, settings )
%
% self = fromFreeSurferSegmentation (
%   self,
%   segmentation,
%   settings
% )
%
% Builds a finite element mesh from a surface segmentation generated by FreeSurfer.
%
% Inputs:
%
% - self
%
%   An empty tetrahedral mesh.
%
% - segmentation
%
%   The required surface segmentation.
%
% - settings
%
%   The settings used in mesh generation.
%
% Outputs:
%
% - self
%
%   An instance of core.TetraMesh.
%

    arguments
        self (1,1) core.TetraMesh
        segmentation (1,1) core.FreeSurferSegmentation
        settings (1,1) core.MeshSettings = core.MeshSettings
    end % arguments

    % TODO: mesh building algorithm.

end % function
