%Copyright © 2018- Sampsa Pursiainen & ZI Development Team
%See: https://github.com/sampsapursiainen/zeffiro_interface
if not(isfield(zef,'iasroi_rec_source'));
    zef.iasroi_rec_source = [0 0 0 0 0 0 0 3 1];
end;
if not(isfield(zef,'iasroi_roi_mode'));
    zef.iasroi_roi_mode = 3;
end;
if not(isfield(zef,'iasroi_roi_sphere'));
    zef.iasroi_roi_sphere = [0 0 0 15];
end;
if not(isfield(zef,'iasroi_roi_threshold'));
    zef.iasroi_roi_threshold = 0.5;
end;
if not(isfield(zef,'iasroi_hyperprior'));
    zef.iasroi_hyperprior = 1;
end;
if not(isfield(zef,'iasroi_n_map_iterations'));
    zef.iasroi_n_map_iterations = 25;
end;
if not(isfield(zef,'iasroi_pcg_tol'));
    zef.iasroi_pcg_tol = 1e-8;
end;
if not(isfield(zef,'iasroi_sampling_frequency'));
    zef.iasroi_sampling_frequency = 1025;
end;
if not(isfield(zef,'iasroi_low_cut_frequency'));
    zef.iasroi_low_cut_frequency = 7;
end;
if not(isfield(zef,'iasroi_high_cut_frequency'));
    zef.iasroi_high_cut_frequency = 9;
end;
if not(isfield(zef,'iasroi_data_segment'));
    zef.iasroi_data_segment = 1;
end;
if not(isfield(zef,'iasroi_normalize_data'));
    zef.iasroi_normalize_data = 1;
end;

if not(isfield(zef,'iasroi_time_1'));
    zef.iasroi_time_1 = 0;
end;
if not(isfield(zef,'iasroi_time_2'));
    zef.iasroi_time_2 = 0;
end;
if not(isfield(zef,'iasroi_time_3'));
    zef.iasroi_time_3 = 0;
end;
if not(isfield(zef,'iasroi_number_of_frames'));
    zef.iasroi_number_of_frames = 1;
end;

zef.iasroi_snr = zef.inv_snr;

set(zef.h_iasroi_rec_source_8 ,'string',num2str(zef.iasroi_rec_source(1,8)));
set(zef.h_iasroi_rec_source_9 ,'value',zef.iasroi_rec_source(1,9));
set(zef.h_iasroi_roi_mode ,'value',zef.iasroi_roi_mode);
set(zef.h_iasroi_roi_sphere_1 ,'string',num2str(zef.iasroi_roi_sphere(:,1)'));
set(zef.h_iasroi_roi_sphere_2 ,'string',num2str(zef.iasroi_roi_sphere(:,2)'));
set(zef.h_iasroi_roi_sphere_3 ,'string',num2str(zef.iasroi_roi_sphere(:,3)'));
set(zef.h_iasroi_roi_sphere_4 ,'string',num2str(zef.iasroi_roi_sphere(:,4)'));
set(zef.h_iasroi_hyperprior ,'value',zef.iasroi_hyperprior);
set(zef.h_iasroi_snr ,'string',num2str(zef.iasroi_snr));
set(zef.h_iasroi_n_map_iterations ,'string',num2str(zef.iasroi_n_map_iterations ));
set(zef.h_iasroi_sampling_frequency ,'string',num2str(zef.iasroi_sampling_frequency));
set(zef.h_iasroi_low_cut_frequency ,'string',num2str(zef.iasroi_low_cut_frequency));
set(zef.h_iasroi_high_cut_frequency ,'string',num2str(zef.iasroi_high_cut_frequency));
set(zef.h_iasroi_normalize_data ,'value',zef.iasroi_normalize_data);
set(zef.h_iasroi_time_1 ,'string',num2str(zef.iasroi_time_1));
set(zef.h_iasroi_time_2 ,'string',num2str(zef.iasroi_time_2));
set(zef.h_iasroi_time_3 ,'string',num2str(zef.iasroi_time_3));
set(zef.h_iasroi_number_of_frames ,'string',num2str(zef.iasroi_number_of_frames));

if get(zef.h_iasroi_roi_mode,'value')==1;
    set(zef.h_iasroi_plot_roi,'enable','on');
    set(zef.h_iasroi_plot_source,'enable','on');
    set(zef.h_iasroi_roi_sphere_1,'enable','on');
    set(zef.h_iasroi_roi_sphere_2,'enable','on');
    set(zef.h_iasroi_roi_sphere_3,'enable','on');
    set(zef.h_iasroi_roi_sphere_4,'enable','on');
    set(zef.h_iasroi_rec_source_8,'enable','on');
    set(zef.h_iasroi_rec_source_9,'enable','on');
    set(zef.h_iasroi_roi_threshold,'enable','off');
else;
    set(zef.h_iasroi_roi_sphere_1,'enable','off');
    set(zef.h_iasroi_roi_sphere_2,'enable','off');
    set(zef.h_iasroi_roi_sphere_3,'enable','off');
    set(zef.h_iasroi_roi_sphere_4,'enable','off');
    set(zef.h_iasroi_rec_source_8,'enable','off');
    set(zef.h_iasroi_rec_source_9,'enable','off');
    set(zef.h_iasroi_plot_roi,'enable','off');
    set(zef.h_iasroi_plot_source,'enable','off');
end;
if get(zef.h_iasroi_roi_mode,'value')==2;
    set(zef.h_iasroi_roi_threshold,'enable','on');
else;
    set(zef.h_iasroi_roi_threshold,'enable','off');
end;
