function [L_eeg, dipole_locations, dipole_directions] = lead_field_eeg_fem( ...
    zef, ...
    nodes, ...
    elements, ...
    sigma, ...
    electrodes, ...
    p_nearest_neighbour_inds, ...
    optimization_system_type, ...
    varargin ...
)
[L_eeg, dipole_locations, dipole_directions] = lead_field_eeg_fem( ...
    zef, ...
    nodes, ...
    elements, ...
    sigma, ...
    electrodes, ...
    p_nearest_neighbour_inds, ...
    optimization_system_type, ...
    varargin ...
);
end