function [L_eit, bg_data, dof_positions, dof_directions, dof_ind, dof_count] = lead_field_eit_fem( ...
    zef, ...
    nodes, ...
    elements, ...
    sigma, ...
    electrodes, ...
    p_nearest_neighbour_inds, ...
    varargin ...
)
[L_eit, bg_data, dof_positions, dof_directions, dof_ind, dof_count] = lead_field_eit_fem( ...
    zef, ...
    nodes, ...
    elements, ...
    sigma, ...
    electrodes, ...
    p_nearest_neighbour_inds, ...
    varargin ...
);
end