function [Lsignx, Lsigny, Lsignz] = zef_lead_field_sign( ...
    p_source_positions, ...
    p_electrode_positions, ...
    p_L ...
)
[Lsignx, Lsigny, Lsignz] = zef_lead_field_sign( ...
    p_source_positions, ...
    p_electrode_positions, ...
    p_L ...
);
end