zeffiro_interface('start_mode','nodisplay',...
    'open_project', 'C:\Users\Paavo\Documents\MATLAB\zeffiro_interface\data\P20N20_SEP_timeseries_multiLF_kalmanSettings.mat', ...
    'run_script', 'zef_kf_start',...
    'run_script', '[zef.reconstruction, zef.reconstruction_information] = zef_KF;', ...
    'save_project', 'C:\Users\Paavo\Documents\MATLAB\zeffiro_interface\data\P20N20_SEP_timeseries_multiLF_kalmanSettings2.mat', ...
    'exit_zeffiro')